# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

# =============================================
# Hugo Theme Stack - Left Sidebar Menu Config
# Author: Albert-Mi
# =============================================

###########################
# 1. Social Icons Section #
###########################

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Albert-Mi"

[social.params]
icon = "brand-github"   # 官方 GitHub 图标

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com"

[social.params]
icon = "brand-twitter"  # 官方 Twitter 图标


##########################
# 2. Main Menu Section   #
##########################

# 首页
# [[main]]
# identifier = "home"
# name = "Home"
# url = "/"
# weight = 1

# [main.params]
# icon = "home"

# 个人简历
[[main]]
name   = "About me"
url    = "/about/"
weight = 1
# Stack expects an icon name; we'll add assets/icons/user.svg below.
[main.params]
icon = "user"


# 书签页（Bookmarks）
[[main]]
identifier = "bookmarks"
name = "Bookmarks"
url = "/bookmarks/"
weight = 2

[main.params]
icon = "bookmark"

# 归档页
[[main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 3

[main.params]
icon = "archive"

# 搜索页
[[main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 4

[main.params]
icon = "search"
