# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

# =============================================
# Hugo Theme Stack - Left Sidebar Menu Config
# Author: Albert-Mi
# =============================================

###########################
# 1. Social Icons Section #
###########################

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Albert-Mi"

[social.params]
icon = "brand-github"   # 官方 GitHub 图标

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com"

[social.params]
icon = "brand-twitter"  # 官方 Twitter 图标


##########################
# 2. Main Menu Section   #
##########################

# 首页
# [[main]]
# identifier = "home"
# name = "Home"
# url = "/"
# weight = 1

# [main.params]
# icon = "home"

# 个人简历
[[main]]
name   = "About me"
url    = "/about/"
weight = 1
# Small inline SVG logo (a simple user avatar). You can replace with your own.
pre = """<svg width="18" height="18" viewBox="0 0 24 24" fill="none"
xmlns="http://www.w3.org/2000/svg" style="vertical-align:-3px;margin-right:8px;">
<path d="M12 12a5 5 0 1 0-5-5 5 5 0 0 0 5 5Zm0 2c-4.418 0-8 2.239-8 5v1h16v-1c0-2.761-3.582-5-8-5Z"
stroke="currentColor" stroke-width="1.5" fill="none"/></svg>"""


# 书签页（Bookmarks）
[[main]]
identifier = "bookmarks"
name = "Bookmarks"
url = "/bookmarks/"
weight = 2

[main.params]
icon = "bookmark"

# 归档页
[[main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 3

[main.params]
icon = "archive"

# 搜索页
[[main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 4

[main.params]
icon = "search"
